[package]
name = "raymarching_bachelor"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = {version = "0.16.0", features = ["wayland", "dynamic_linking"]}
bevy_egui = "0.34.1"

# optimizations for dependencies, but not our code
[profile.dev.package."*"]
opt-level = 3
